// Generates lib/widgets/world_map/land_mask.dart: a bit mask telling for each
// cell of the world map's dot grid whether its center lies on land.
//
// Input is the public domain Natural Earth 1:50m land data:
//   https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson
//
//   dart run tool/generate_land_mask.dart path/to/ne_50m_land.geojson
//
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

// Keep in sync with the constants written below.
const step = 1.2; // degrees per cell
const north = 84.0; // northern edge of the map
const south = -60.0; // southern edge; Antarctica is left out
const outputPath = 'lib/widgets/world_map/land_mask.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('Usage: dart run tool/generate_land_mask.dart <land.geojson>');
    exit(64);
  }
  final features = (jsonDecode(File(args.single).readAsStringSync())
      as Map<String, dynamic>)['features'] as List;
  final rings = <List<List<double>>>[
    for (final feature in features)
      for (final polygon in _polygons(feature['geometry']))
        for (final ring in polygon)
          [
            for (final point in ring as List)
              [(point[0] as num).toDouble(), (point[1] as num).toDouble()],
          ],
  ];

  final columns = (360 / step).round();
  final rows = ((north - south) / step).round();
  final bits = Uint8List((columns * rows + 7) ~/ 8);
  var landCells = 0;

  for (var row = 0; row < rows; row++) {
    final latitude = north - (row + 0.5) * step;
    // Longitudes where the parallel crosses a coastline (even-odd rule).
    final crossings = <double>[];
    for (final ring in rings) {
      for (var i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        final (x1, y1) = (ring[j][0], ring[j][1]);
        final (x2, y2) = (ring[i][0], ring[i][1]);
        if ((y1 > latitude) != (y2 > latitude)) {
          crossings.add(x1 + (latitude - y1) * (x2 - x1) / (y2 - y1));
        }
      }
    }
    crossings.sort();
    for (var column = 0; column < columns; column++) {
      final longitude = -180 + (column + 0.5) * step;
      final inside = crossings.where((x) => x < longitude).length.isOdd;
      if (inside) {
        final index = row * columns + column;
        bits[index >> 3] |= 1 << (index & 7);
        landCells++;
      }
    }
  }

  File(outputPath).writeAsStringSync('''
// Generated by tool/generate_land_mask.dart from Natural Earth 1:50m land
// data (public domain). Do not edit.

/// Size of one dot grid cell in degrees.
const landMaskStep = $step;

/// Latitude of the northern and southern map edge.
const landMaskNorth = $north;
const landMaskSouth = $south;

const landMaskColumns = $columns;
const landMaskRows = $rows;

/// One bit per cell, row by row from the north, least significant bit first.
const landMaskBase64 =
    '${base64Encode(bits)}';
''');
  print('Wrote $landCells land cells of ${columns * rows} to $outputPath');
}

Iterable<List> _polygons(Map<String, dynamic> geometry) {
  final coordinates = geometry['coordinates'] as List;
  return switch (geometry['type']) {
    'Polygon' => [coordinates],
    'MultiPolygon' => coordinates.cast<List>(),
    _ => const [],
  };
}
