import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:timezone/timezone.dart' as tz;

/// Time zone rules of all zones in cities.json, generated by
/// `tool/generate_time_zones.dart`.
const timeZoneAsset = 'assets/data/timezones.tzf';

Future<void> initializeTimeZones(AssetBundle bundle) async {
  final data = await bundle.load(timeZoneAsset);
  tz.initializeDatabase(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
}

/// Looks up [timeZone]. An unknown zone falls back to UTC instead of
/// throwing, so a single city can never break the whole screen.
tz.Location findLocation(String timeZone) {
  try {
    return tz.getLocation(timeZone);
  } on tz.LocationNotFoundException {
    return tz.UTC;
  }
}

DateFormat clockFormat({required bool use24hr, required bool showSeconds}) {
  if (showSeconds) {
    return use24hr ? DateFormat('Hms') : DateFormat('hh:mm:ss a');
  }
  return use24hr ? DateFormat('Hm') : DateFormat('hh:mm a');
}

String formatTimeInZone(
  String timeZone, {
  required bool use24hr,
  required bool showSeconds,
  DateTime? now,
}) {
  final location = findLocation(timeZone);
  final time = now == null
      ? tz.TZDateTime.now(location)
      : tz.TZDateTime.from(now, location);
  return clockFormat(use24hr: use24hr, showSeconds: showSeconds).format(time);
}

/// Offset of [timeZone] relative to the device's local time zone.
Duration differenceToLocal(String timeZone, {DateTime? now}) {
  final instant = now ?? DateTime.now();
  final cityOffset =
      tz.TZDateTime.from(instant, findLocation(timeZone)).timeZoneOffset;
  return cityOffset - instant.timeZoneOffset;
}

/// Formats an offset like `+02:00` or `-05:30`.
String formatOffset(Duration offset) {
  final totalMinutes = offset.inMinutes;
  final sign = totalMinutes < 0 ? '-' : '+';
  final absoluteMinutes = totalMinutes.abs();
  final hours = (absoluteMinutes ~/ 60).toString().padLeft(2, '0');
  final minutes = (absoluteMinutes % 60).toString().padLeft(2, '0');
  return '$sign$hours:$minutes';
}

/// Parses an offset like `+05:30` into minutes, or `null` if malformed.
int? parseUtcOffset(String utc) {
  final match = RegExp(r'([+-])(\d{2}):(\d{2})').firstMatch(utc);
  if (match == null) return null;
  final minutes = int.parse(match.group(2)!) * 60 + int.parse(match.group(3)!);
  return match.group(1) == '-' ? -minutes : minutes;
}

/// Converts a wttr.in time like `07:11 AM` to the user's clock format.
/// Returns `null` for values such as `No sunrise` (polar day/night).
String? formatWttrTime(String raw, {required bool use24hr}) {
  final DateTime time;
  try {
    time = DateFormat('hh:mm a', 'en_US').parseStrict(raw.trim());
  } on FormatException {
    return null;
  }
  return (use24hr ? DateFormat('HH:mm') : DateFormat('hh:mm a')).format(time);
}

/// Time of a past update; includes the date unless it was on the same day.
String formatUpdateTime(
  DateTime time, {
  required bool use24hr,
  required String locale,
  DateTime? now,
}) {
  final today = now ?? DateTime.now();
  final clock = clockFormat(use24hr: use24hr, showSeconds: false).format(time);
  final sameDay = time.year == today.year &&
      time.month == today.month &&
      time.day == today.day;
  return sameDay ? clock : '${DateFormat.MMMd(locale).format(time)}, $clock';
}

/// Current wall-clock time of [timeZone], suitable for comparing with the
/// local times in a weather forecast. It is stored as a UTC [DateTime] so
/// that the device's own daylight saving time never shifts it.
DateTime wallClockIn(String timeZone, {DateTime? now}) {
  final time = tz.TZDateTime.from(
      now ?? DateTime.now(), findLocation(timeZone));
  return DateTime.utc(
      time.year, time.month, time.day, time.hour, time.minute, time.second);
}

/// Number of calendar days from [from] to [to], ignoring the time of day.
/// Computed on UTC dates so a daylight saving change (a 23 or 25 hour day)
/// does not distort the result.
int calendarDaysBetween(DateTime from, DateTime to) {
  return DateTime.utc(to.year, to.month, to.day)
      .difference(DateTime.utc(from.year, from.month, from.day))
      .inDays;
}
