name: Build & Release Signed APK

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Get Flutter version from pubspec.yaml
        id: flutter_version
        run: |
          FLUTTER_VERSION=$(grep 'flutter:' pubspec.yaml | head -1 | awk '{print $2}' | tr -d '^"')
          echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter_version.outputs.flutter_version }}


      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=key.jks
          EOF

      - name: Get dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test

      - name: Build signed release APK
        run: flutter build apk --release

      - name: Rename APK with version
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/worldclockv2_v${VERSION}_android_arm64.apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: worldclockv2-android-build
          path: |
            build/app/outputs/flutter-apk/worldclockv2*.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/worldclockv2_v${{ steps.version.outputs.version }}_android_arm64.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
